version: "3.7"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'

  django:
    stdin_open: true
    build:
      context: .
    depends_on:
      - postgres
      # command: "8080"
    environment:
      - DJANGO_SETTINGS_MODULE=psycopg_performance.settings
      - DATABASE_URL=psql://test:test@postgres:5432/test
    init: true
    ports:
      - "54321:8000"
    volumes:
      - .:/var/www/app

volumes:
  pgdata:
